### ISSUE TITLE
Añadir y eliminar registros de proveedores

### ISSUE THREAD

**Issue by BenzoElTerrible** [benjaminfisherp/Taller_1_TPW#3]

**Comment by BRIKXO** [comment]
Historia de usuario:
Como administrador quiero poder mantener información de proveedores para ser usada en el módulo de ingreso.

Criterios de aceptación:
1. El administrador hace click en el modulo de proveedores
2. El administrador logra visualizar, y ver los botones de añadir y eliminar
3. El administrador hace click en añadir o eliminar

Resultado:
El administrador logra añadir o eliminar proveedores
