### ISSUE TITLE
Añadir y eliminar registros de frutas

### ISSUE THREAD

**Issue by BenzoElTerrible** [benjaminfisherp/Taller_1_TPW#4]
Historia de Usuario:
Como usuario quiero poder ingresar fruta al sistema (centro de acopio)

Criterios de aceptación:

1. El usuario inicia sesión.
2. El usuario hace click el boton Productos del NavBar
3. Usuario hace click en boton Especie
4. Usuario hace click en boton añadir

Resultados: El usuario logra ingresar / añadir fruta al sistema

Historia de Usuario:
Como usuario quiero poder sacar fruta del sistema (centro de acopio)

Criterios de aceptación:

1. El usuario inicia sesión.
2. El usuario hace click el boton Productos del NavBar
3. Usuario hace click en boton Especie
4. Usuario hace click en boton Eliminar
5.
Resultados: El usuario logra eliminar fruta al sistema

**Comment by BRIKXO** [comment]
Historia de Usuario:
Como usuario quiero poder ingresar fruta al sistema (centro de acopio)

Criterios de aceptación:
1. Como usuario de la plataforma (Administrador y usuario) hago click en el modulo de ingreso
2. Hago click en el boton agregar de la tabla de ingreso.

Resultado:
Se logra ingresar fruta al sistema.
