### ISSUE TITLE
Añadir y eliminar registros de clientes

### ISSUE THREAD

**Issue by BenzoElTerrible** [benjaminfisherp/Taller_1_TPW#8]
Historia de Usuario:
Como administrador quiero poder añadir información de cliente para ser usada en el módulo de egreso.

Criterio de aceptacion

1. Administrador inicia sesión
2. Administrador clickea boton de Productos del NavBar
3. Administrador clickea boton Cliente
4. Administrador clickea boton Agregar

Resultado: Se añade informacion de nuevo cliente.

Historia de Usuario:
Como administrador quiero poder eliminar información de cliente para estar actualizada en el módulo de egreso.

Criterio de aceptacion

1. Administrador inicia sesión
2. Administrador clickea boton de Productos del NavBar
3. Administrador clickea boton Cliente
4. Administrador clickea boton Eliminar

Resultado: Se elimina informacion de nuevo cliente.

**Comment by BRIKXO** [comment]
Historia de Usuario:
Como administrador quiero poder mantener información de cliente para ser usada en el módulo de egreso.

Criterios de aceptación:
1. El administrador hace click en la tabla de clientes.
2. El administrador logra visualizar los datos del cliente.

Resultado:
El administrador logra mantener la información del cliente para ser usada en el modulo de egreso
